monitor.alsa.rules = [
  {
    matches = [
      {
        node.name = "alsa_output.platform-tcl-acpi-card.stereo-fallback"
      }
    ]
    actions = {
      update-props = {
        audio.format   = "S16LE"
        audio.rate     = 48000
        audio.channels = 2
        session.suspend-timeout-seconds = 0
      }
    }
  }
]
